name: k8s-streaming-lab

networks:
  streaming-net:
    driver: bridge

volumes:
  redpanda-data: null

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v26.1.14
    container_name: redpanda
    command:
      - redpanda start
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092
      - --smp 1
      - --memory 1G
      - --overprovisioned
      - --node-id 0
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    ports:
      - "19092:9092"
    networks:
      - streaming-net
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  console:
    image: docker.redpanda.com/redpandadata/console:v3.11.0
    container_name: redpanda-console
    environment:
      - KAFKA_BROKERS=redpanda:9092
    ports:
      - "8080:8080"
    depends_on:
      redpanda:
        condition: service_healthy

    networks:
      - streaming-net

  producer:
    build:
      context: .
      dockerfile: src/k8s-streaming-lab-producer/Dockerfile
    container_name: producer
    environment:
      - Kafka__BootstrapServers=redpanda:9092
      - Kafka__Topic=streaming-events
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - streaming-net