apiVersion: v1
kind: Service
metadata:
  name: redpanda-service
  namespace: streaming-platform
  labels:
    app.kubernetes.io/name: redpanda-service
    app.kubernetes.io/part-of: streaming-platform

spec:
  clusterIP: None

  selector:
    app.kubernetes.io/name: redpanda

  ports:
    - name: kafka
      port: 9092
      targetPort: kafka